"""The P1 arithmetic projection generated by transparent arities."""

from __future__ import annotations

from functools import lru_cache
from math import log2

from prime_arity import is_transparent_arity, trial_is_prime


@lru_cache(maxsize=None)
def transparent_factorization(value: int) -> tuple[tuple[int, int], ...]:
    if value < 1:
        raise ValueError("arithmetic identity must be positive")
    remainder = value
    factors = []
    arity = 2
    while arity * arity <= remainder:
        if is_transparent_arity(arity) and remainder % arity == 0:
            exponent = 0
            while remainder % arity == 0:
                remainder //= arity
                exponent += 1
            factors.append((arity, exponent))
        arity += 1
    if remainder > 1:
        # Trial division above already proves irreducibility.  The
        # prime-arity theorem then identifies the remainder as transparent;
        # avoid rebuilding its entire binomial row merely as an audit.
        if not trial_is_prime(remainder):
            raise AssertionError("remaining irreducible arity was not transparent")
        factors.append((remainder, 1))
    return tuple(factors)


def reconstruct_factorization(factors: tuple[tuple[int, int], ...]) -> int:
    value = 1
    for arity, exponent in factors:
        # By the prime-arity theorem this efficient primality check is
        # equivalent to rebuilding the full transparency row.
        if not trial_is_prime(arity) or exponent < 1:
            raise ValueError("factorization uses a nontransparent arity")
        value *= arity**exponent
    return value


def binary_distinction_cost(value: int) -> float:
    """Additive capacity cost in binary distinction units."""

    return sum(
        exponent * log2(arity)
        for arity, exponent in transparent_factorization(value)
    )


def generated_mobius(value: int) -> int:
    """Inversion of the independent transparent-arity selection lattice."""

    factors = transparent_factorization(value)
    if any(exponent > 1 for _, exponent in factors):
        return 0
    return (-1) ** len(factors)


def finite_dirichlet_sum(limit: int, parameter: complex) -> complex:
    if limit < 1:
        raise ValueError("limit must be positive")
    return sum(value ** (-parameter) for value in range(1, limit + 1))


def audit(limit: int) -> dict:
    if limit < 2:
        raise ValueError("limit must be at least two")
    return {
        "status": (
            "P1 arithmetic realization generated after transparent arities; "
            "not identified with native mathematics of another perspective"
        ),
        "limit": limit,
        "all_identities_reconstruct_from_transparent_arities": all(
            reconstruct_factorization(transparent_factorization(value)) == value
            for value in range(1, limit + 1)
        ),
        "all_binary_costs_equal_log2_identity": all(
            abs(binary_distinction_cost(value) - log2(value)) < 1e-12
            for value in range(1, limit + 1)
        ),
        "mobius_values": {
            str(value): generated_mobius(value)
            for value in range(1, min(limit, 50) + 1)
        },
        "generated_character": (
            "additive cost c(n)=log_2(n) gives multiplicative analytic "
            "character 2^(-s*c(n))=n^(-s)"
        ),
        "generated_euler_region": (
            "sum_n n^(-s)=product_{p transparent}(1-p^(-s))^(-1) "
            "for Re(s)>1"
        ),
    }
