"""Distinguishability generated by the native extension relation itself.

No arbitrary prefix word is assigned here.  A source form is observed only
through binary incidence questions already present in the extension relation:
whether a strict past form occurs below it and whether it can occur inside a
future context.  Equal observation signatures remain one unresolved fiber.
"""

from __future__ import annotations

from collections import Counter
from itertools import combinations

from native_extension import NativeExtensionData, incidence_components
from primitive import History, native_key
from refinement_invariant import characteristic_coefficients


NativeKey = tuple


def connected_keys(data: NativeExtensionData, level: int | None = None) -> tuple[NativeKey, ...]:
    levels = range(1, data.max_events + 1) if level is None else (level,)
    return tuple(
        key
        for event_count in levels
        for key, history in data.representatives[event_count].items()
        if len(incidence_components(history)) == 1
    )


def child_map(data: NativeExtensionData) -> dict[NativeKey, frozenset[NativeKey]]:
    children: dict[NativeKey, set[NativeKey]] = {key: set() for key in data.level}
    for child, parents in data.parents.items():
        for parent in parents:
            children[parent].add(child)
    return {key: frozenset(values) for key, values in children.items()}


def descendant_map(data: NativeExtensionData) -> dict[NativeKey, frozenset[NativeKey]]:
    children = child_map(data)
    descendants: dict[NativeKey, set[NativeKey]] = {key: set() for key in data.level}
    for key in sorted(data.level, key=data.level.__getitem__, reverse=True):
        for child in children[key]:
            descendants[key].add(child)
            descendants[key].update(descendants[child])
    return {key: frozenset(values) for key, values in descendants.items()}


def strict_past_signature(data: NativeExtensionData, key: NativeKey) -> frozenset[NativeKey]:
    return data.ancestors[key]


def complete_context_signature(
    data: NativeExtensionData,
    key: NativeKey,
    descendants: dict[NativeKey, frozenset[NativeKey]] | None = None,
) -> tuple[frozenset[NativeKey], frozenset[NativeKey]]:
    future = descendant_map(data) if descendants is None else descendants
    return data.ancestors[key], future[key]


def fibers(
    keys: tuple[NativeKey, ...],
    signature,
) -> tuple[tuple[NativeKey, ...], ...]:
    classes: dict[object, list[NativeKey]] = {}
    for key in keys:
        classes.setdefault(signature(key), []).append(key)
    return tuple(
        tuple(values)
        for _, values in sorted(classes.items(), key=lambda item: repr(item[0]))
    )


def fiber_size_histogram(classes: tuple[tuple[NativeKey, ...], ...]) -> dict[int, int]:
    return dict(sorted(Counter(map(len, classes)).items()))


def multiply_polynomials(
    left: dict[int, int],
    right: dict[int, int],
) -> dict[int, int]:
    result: dict[int, int] = {}
    for left_power, left_coefficient in left.items():
        for right_power, right_coefficient in right.items():
            power = left_power + right_power
            result[power] = result.get(power, 0) + left_coefficient * right_coefficient
    return {power: coefficient for power, coefficient in result.items() if coefficient}


def ambiguity_characteristic(
    classes: tuple[tuple[NativeKey, ...], ...],
) -> dict[int, int]:
    """Characteristic of the product of all nontrivial refinement fibers."""

    result = {0: 1}
    for source_fiber in classes:
        if len(source_fiber) > 1:
            result = multiply_polynomials(
                result,
                characteristic_coefficients(len(source_fiber)),
            )
    return result


def evaluate(coefficients: dict[int, int], value: int) -> int:
    return sum(coefficient * value**power for power, coefficient in coefficients.items())


def future_separation_delay(
    data: NativeExtensionData,
    left: NativeKey,
    right: NativeKey,
) -> int | None:
    """Least audited future rank containing a context for exactly one form."""

    if data.level[left] != data.level[right]:
        raise ValueError("delay compares forms at one extension rank")
    source_level = data.level[left]
    for target_level in range(source_level + 1, data.max_events + 1):
        if any(
            ((left in data.ancestors[target]) != (right in data.ancestors[target]))
            for target in data.representatives[target_level]
        ):
            return target_level - source_level
    return None


def disjoint_atomic_context(history: History, arity: int) -> History:
    """Append the source-allowed occurrence sharing no resultants."""

    existing = {vertex for event in history for vertex in event}
    next_token = max(existing) + 1 if existing else 0
    return history + (tuple(range(next_token, next_token + arity)),)


def disjoint_context_isolates_connected_form(history: History, arity: int) -> bool:
    """Verify the one-step contextual separation construction.

    For a connected m-event form H with m>1, E=H disjoint-union one atomic
    event has exactly one connected m-event deletion: deleting the new event
    recovers H.  Every other deletion leaves the new atom as a separate
    component.
    """

    if len(history) <= 1 or len(incidence_components(history)) != 1:
        raise ValueError("the witness theorem concerns connected rank > 1 forms")
    context = disjoint_atomic_context(history, arity)
    source_key = native_key(history, arity)
    connected_deletions = []
    for index in range(len(context)):
        deletion = context[:index] + context[index + 1 :]
        if len(incidence_components(deletion)) == 1:
            connected_deletions.append(native_key(deletion, arity))
    return connected_deletions == [source_key]


def audit(data: NativeExtensionData) -> dict:
    descendants = descendant_map(data)
    layers = []
    all_past_fibers: list[tuple[NativeKey, ...]] = []
    all_context_fibers: list[tuple[NativeKey, ...]] = []

    for level in range(1, data.max_events + 1):
        keys = connected_keys(data, level)
        past = fibers(keys, lambda key: strict_past_signature(data, key))
        context = fibers(
            keys,
            lambda key: complete_context_signature(data, key, descendants),
        )
        all_past_fibers.extend(past)
        all_context_fibers.extend(context)

        pair_delays = [
            future_separation_delay(data, left, right)
            for source_fiber in past
            if len(source_fiber) > 1
            for left, right in combinations(source_fiber, 2)
        ]
        delay_histogram = Counter(
            "not_resolved_within_horizon" if delay is None else str(delay)
            for delay in pair_delays
        )
        layers.append(
            {
                "events_P1_coordinate": level,
                "connected_native_forms": len(keys),
                "strict_past_observation_classes": len(past),
                "strict_past_fiber_size_histogram": fiber_size_histogram(past),
                "complete_audited_context_classes": len(context),
                "complete_context_fiber_size_histogram": fiber_size_histogram(context),
                "past_indistinguishable_pair_future_delay_histogram": dict(
                    sorted(delay_histogram.items())
                ),
            }
        )

    past_tuple = tuple(all_past_fibers)
    context_tuple = tuple(all_context_fibers)
    past_characteristic = ambiguity_characteristic(past_tuple)
    context_characteristic = ambiguity_characteristic(context_tuple)
    return {
        "status": (
            "binary existence observations from the native extension relation; "
            "class counts are P1 audit metadata"
        ),
        "arity_P1_coordinate": data.arity,
        "layers": layers,
        "strict_past_global_fiber_histogram": fiber_size_histogram(past_tuple),
        "complete_context_global_fiber_histogram": fiber_size_histogram(context_tuple),
        "strict_past_ambiguity_characteristic_by_exponent": {
            str(power): coefficient
            for power, coefficient in sorted(past_characteristic.items(), reverse=True)
        },
        "strict_past_binary_evaluation": evaluate(past_characteristic, 2),
        "complete_context_ambiguity_characteristic_by_exponent": {
            str(power): coefficient
            for power, coefficient in sorted(context_characteristic.items(), reverse=True)
        },
        "complete_context_binary_evaluation": evaluate(context_characteristic, 2),
        "one_step_disjoint_context_theorem_verified_on_audit": all(
            disjoint_context_isolates_connected_form(history, data.arity)
            for level in range(2, data.max_events + 1)
            for history in data.representatives[level].values()
            if len(incidence_components(history)) == 1
        ),
        "interpretation": (
            "interaction context refines perception fibers without altering any "
            "underlying native incidence form"
        ),
    }
