"""Cross-boundary completion generated by complete prime-arity fibres.

The source remains the distinction rule.  This module performs only its P1
arithmetic realization:

* retain the full character group of every finite base-p digit fibre;
* take the complete nontrivial trace at the least digit boundary;
* use the binary trace's complete-difference transform to cross Re(s)=1; and
* audit the exact interaction and zero constraints of all prime traces.

No zeta functional equation, gamma completion, random model, or assumed zero
location is used.
"""

from __future__ import annotations

from cmath import exp
from fractions import Fraction
from itertools import product
from math import comb, ldexp, log, pi

from prime_arity import is_transparent_arity


def _require_transparent(prime_arity: int) -> None:
    if not is_transparent_arity(prime_arity):
        raise ValueError("character fibre requires a transparent arity")


def digit_vector(value: int, prime_arity: int, places: int) -> tuple[int, ...]:
    """The first ``places`` generated capacity digits of ``value``."""

    _require_transparent(prime_arity)
    if value < 0 or places < 0:
        raise ValueError("value and places must be nonnegative")
    digits = []
    remainder = value
    for _ in range(places):
        digits.append(remainder % prime_arity)
        remainder //= prime_arity
    return tuple(digits)


def complete_character_indices(
    prime_arity: int,
    places: int,
) -> tuple[tuple[int, ...], ...]:
    """All characters of the finite digit group (Z/pZ)^places.

    The earlier one-index family ``(r, r, ..., r)`` is only the diagonal of
    this group.  Completeness requires independent character indices at every
    generated digit place.
    """

    _require_transparent(prime_arity)
    if places < 0:
        raise ValueError("places must be nonnegative")
    return tuple(product(range(prime_arity), repeat=places))


def diagonal_character_indices(
    prime_arity: int,
    places: int,
) -> tuple[tuple[int, ...], ...]:
    """The previously retained diagonal subfibre, for comparison only."""

    _require_transparent(prime_arity)
    if places < 0:
        raise ValueError("places must be nonnegative")
    return tuple((index,) * places for index in range(prime_arity))


def digit_character(
    value: int,
    prime_arity: int,
    character_indices: tuple[int, ...],
) -> complex:
    """Evaluate one full-fibre character on an integer identity."""

    _require_transparent(prime_arity)
    if any(not 0 <= index < prime_arity for index in character_indices):
        raise ValueError("character index outside the prime-arity range")
    digits = digit_vector(value, prime_arity, len(character_indices))
    phase = sum(index * digit for index, digit in zip(character_indices, digits))
    return exp(2j * pi * phase / prime_arity)


def character_orthogonality_sum(
    left: int,
    right: int,
    prime_arity: int,
    places: int,
) -> complex:
    """Sum chi(left) conjugate(chi(right)) over the complete fibre."""

    total = 0j
    for indices in complete_character_indices(prime_arity, places):
        left_value = digit_character(left, prime_arity, indices)
        right_value = digit_character(right, prime_arity, indices)
        total += left_value * right_value.conjugate()
    return total


def complete_digit_trace(
    value: int,
    prime_arity: int,
    place: int = 0,
) -> int:
    """Negative sum of every nontrivial character at one digit place.

    Character completeness gives this integer-valued trace exactly:

        1-p, if the selected digit is zero;
        1,   otherwise.

    At the least place and for positive ``value``, a zero digit is equivalent
    to divisibility by p.
    """

    _require_transparent(prime_arity)
    if value < 0 or place < 0:
        raise ValueError("value and place must be nonnegative")
    digit = digit_vector(value, prime_arity, place + 1)[place]
    return 1 - prime_arity if digit == 0 else 1


def character_sum_digit_trace(
    value: int,
    prime_arity: int,
    place: int = 0,
) -> complex:
    """Direct character-sum realization of :func:`complete_digit_trace`."""

    _require_transparent(prime_arity)
    digit = digit_vector(value, prime_arity, place + 1)[place]
    return -sum(
        exp(2j * pi * index * digit / prime_arity)
        for index in range(1, prime_arity)
    )


def _positive_power(value: int | float, exponent: complex) -> complex:
    return exp(exponent * log(value))


def complete_difference(parameter: complex, rank: int) -> complex:
    """The rank-n complete distinction of k -> (k+1)^(-parameter)."""

    if rank < 0:
        raise ValueError("rank must be nonnegative")
    return sum(
        (-1 if choice & 1 else 1)
        * comb(rank, choice)
        * _positive_power(choice + 1, -parameter)
        for choice in range(rank + 1)
    )


def binary_hasse_term(parameter: complex, rank: int) -> complex:
    """Stable weighted rank term of the complete binary transform."""

    if rank < 0:
        raise ValueError("rank must be nonnegative")
    # Apply the binary capacity weight before summing.  This avoids forming a
    # huge unweighted finite difference and then multiplying by 2^(-rank-1).
    return sum(
        (-1 if choice & 1 else 1)
        * ldexp(float(comb(rank, choice)), -rank - 1)
        * _positive_power(choice + 1, -parameter)
        for choice in range(rank + 1)
    )


def binary_hasse_eta(parameter: complex, terms: int = 80) -> complex:
    """Globally convergent entire binary boundary numerator.

    H(s) = sum_n 2^(-n-1) sum_k (-1)^k C(n,k) (k+1)^(-s).

    ``terms`` is a numerical truncation only; the mathematical object is the
    locally uniformly convergent infinite series.
    """

    if terms < 1:
        raise ValueError("terms must be positive")
    return sum(binary_hasse_term(parameter, rank) for rank in range(terms))


def binary_hasse_eta_derivative(parameter: complex, terms: int = 80) -> complex:
    """Derivative of the entire binary boundary numerator."""

    if terms < 1:
        raise ValueError("terms must be positive")
    total = 0j
    for rank in range(terms):
        total += sum(
            (-1 if choice & 1 else 1)
            * ldexp(float(comb(rank, choice)), -rank - 1)
            * (-log(choice + 1))
            * _positive_power(choice + 1, -parameter)
            for choice in range(rank + 1)
        )
    return total


def negative_integer_hasse_exact(power: int) -> Fraction:
    """Exact value H(-power) from the terminating difference expansion."""

    if power < 0:
        raise ValueError("power must be nonnegative")
    total = Fraction(0)
    # The complete difference of a degree-power polynomial vanishes above
    # ``power``.  No numerical infinite-series truncation is involved.
    for rank in range(power + 1):
        difference = sum(
            (-1 if choice & 1 else 1)
            * comb(rank, choice)
            * (choice + 1) ** power
            for choice in range(rank + 1)
        )
        total += Fraction(difference, 2 ** (rank + 1))
    return total


def binary_denominator(parameter: complex) -> complex:
    return 1 - _positive_power(2, 1 - parameter)


def continued_zeta(
    parameter: complex,
    terms: int = 80,
    removable_tolerance: float = 1e-10,
) -> complex:
    """Meromorphic continuation generated by the binary trace.

    This is H(s)/(1-2^(1-s)).  At nonzero presentation-lattice points the
    apparent 0/0 is removed by differentiating numerator and denominator.
    The actual pole at s=1 is deliberately not assigned a finite value.
    """

    denominator = binary_denominator(parameter)
    numerator = binary_hasse_eta(parameter, terms)
    if abs(denominator) >= removable_tolerance:
        return numerator / denominator
    if abs(parameter - 1) < removable_tolerance:
        raise ZeroDivisionError("the generated continuation has its pole at s=1")
    derivative_denominator = log(2) * _positive_power(2, 1 - parameter)
    return binary_hasse_eta_derivative(parameter, terms) / derivative_denominator


def prime_boundary_numerator(
    prime_arity: int,
    parameter: complex,
    terms: int = 80,
) -> complex:
    """Entire complete least-digit trace E_p(s).

    E_p(s) = (1-p^(1-s)) Z(s).  The p=2 member is the binary Hasse entire
    function itself, so no removable quotient is taken there.
    """

    _require_transparent(prime_arity)
    if prime_arity == 2:
        return binary_hasse_eta(parameter, terms)
    factor = 1 - _positive_power(prime_arity, 1 - parameter)
    return factor * continued_zeta(parameter, terms)


def prime_trace_dirichlet_partial(
    prime_arity: int,
    parameter: complex,
    limit: int,
) -> complex:
    """Direct partial trace in its initial convergence region."""

    _require_transparent(prime_arity)
    if limit < 1:
        raise ValueError("limit must be positive")
    return sum(
        complete_digit_trace(value, prime_arity, 0)
        * _positive_power(value, -parameter)
        for value in range(1, limit + 1)
    )


def cross_prime_residual(
    left_prime: int,
    right_prime: int,
    parameter: complex,
    terms: int = 80,
) -> complex:
    """Residual of the exact cross-prime compatibility identity."""

    left = prime_boundary_numerator(left_prime, parameter, terms)
    right = prime_boundary_numerator(right_prime, parameter, terms)
    return (
        (1 - _positive_power(right_prime, 1 - parameter)) * left
        - (1 - _positive_power(left_prime, 1 - parameter)) * right
    )


def presentation_zero(prime_arity: int, index: int) -> complex:
    """A nonzero boundary-cancellation lattice coordinate of E_p."""

    _require_transparent(prime_arity)
    if index == 0:
        raise ValueError("index zero is s=1, where cancellation meets the pole")
    return 1 + 2j * pi * index / log(prime_arity)


def audit() -> dict:
    parameter = 0.37 + 4.2j
    complete_size = len(complete_character_indices(3, 2))
    diagonal_size = len(diagonal_character_indices(3, 2))
    return {
        "status": (
            "cross-boundary continuation and zero constraints derived from "
            "the full prime-arity character fibre; no gamma completion, "
            "randomness, or assumed zeta symmetry"
        ),
        "full_p3_two_place_fibre_size": complete_size,
        "old_diagonal_subfibre_size": diagonal_size,
        "full_fibre_strictly_larger_than_diagonal": complete_size > diagonal_size,
        "full_p3_two_place_orthogonality": all(
            abs(
                character_orthogonality_sum(left, right, 3, 2)
                - (9 if left == right else 0)
            )
            < 1e-10
            for left in range(9)
            for right in range(9)
        ),
        "binary_hasse_special_values": {
            "H(0)": binary_hasse_eta(0).real,
            "Z(0)": continued_zeta(0).real,
            "Z(-1)": continued_zeta(-1).real,
            "Z(2)": continued_zeta(2).real,
        },
        "negative_even_binary_zeros_exact": {
            str(-2 * order): str(negative_integer_hasse_exact(2 * order))
            for order in range(1, 4)
        },
        "cross_prime_compatibility_residual_p3_p5": abs(
            cross_prime_residual(3, 5, parameter)
        ),
        "presentation_zero_residuals": {
            str(prime): abs(
                prime_boundary_numerator(prime, presentation_zero(prime, 1))
            )
            for prime in (2, 3, 5)
        },
        "zero_constraint": (
            "for 0<Re(s)<1 every factor 1-p^(1-s) is nonzero, so Z(s)=0 "
            "iff E_p(s)=0 for every (equivalently any) transparent p"
        ),
        "interaction_rank": (
            "one: E_p(s)=(1-p^(1-s)) Z(s); collapsed prime traces share "
            "one analytic carrier and cannot independently force Re(s)=1/2"
        ),
    }
